---
name: AWSCreate
on:
  push:
    branches:
      - main
jobs:
  build-aws-infra:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
  build-terraform:
    runs-on: ubuntu-latest
    needs: build-aws-infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
        with:
         cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      - name: AWS configfure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
  build-aws-infra-notifications:
    runs-on: ubuntu-latest
    needs: build-terraform
    steps:
      - name: Slack Notification
        run: echo "Pls consider this as slack notification"
